name: nwb_datajoint
channels:
  - conda-forge
  - defaults
  - franklab
dependencies:
  - python=3.8
  - jupyterlab>=3.*
  - pydotplus>=2.0.*
  - dask>=2.30
  - pip>=20.2.*
  - position_tools
  - track_linearization
  - skan
  - bottleneck
  - ipympl
  - tqdm
  - nb_conda
  - pip:
    - git+https://github.com/SpikeInterface/spikeinterface.git
    - git+https://github.com/LorenFrankLab/ndx-franklab-novela.git
