name: spyglass
channels:
  - defaults
  - franklab
  - anaconda
  - conda-forge
  - edeno
dependencies:
  - python>=3.8,<3.10
  - jupyterlab>=3.*
  - pydotplus>=2.0.*
  - dask>=2.30
  - pip>=20.2.*
  - position_tools
  - track_linearization
  - replay_trajectory_classification
  - ripple_detection
  - trajectory_analysis_tools
  - matplotlib
  - seaborn
  - bottleneck
  - ipympl
  - tqdm
  - nb_conda
  - skan
  - pyyaml
  - click
  - pymysql>=1.0.*
  - pip:
    - h5py<3
    - mountainsort4
    - git+https://github.com/SpikeInterface/spikeinterface.git
    - pynwb
    - hdmf
    - datajoint>=0.13.6
    - ghostipy
    - sortingview>=0.8
    - git+https://github.com/LorenFrankLab/ndx-franklab-novela.git
