# 1. Install a conda distribution.
#    https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html
# 2. Run: `mamba env create -f environment.yml`
# 3. Activate: `conda activate spyglass`
#
# (lines intentionally left blank)
#
#
name: spyglass
channels:
  - conda-forge
  - defaults
  - franklab
  - edeno
  # - pytorch # dlc-only
  # - anaconda # dlc-only, for cudatoolkit
dependencies:
  - bottleneck
  # - cudatoolkit=11.3 # dlc-only
  # - ffmpeg # dlc-only
  - jupyterlab>=3.*
  # - libgcc # dlc-only
  - pip>=20.2.*
  - pybind11  # req by mountainsort4 -> isosplit5
  - pydotplus>=2.0.*
  - pyfftw<=0.12.0  # ghostipy req. install from conda-forge for Mac ARM
  - python>=3.9,<3.10
  - pytorch<1.12.0
  # - torchaudio # dlc-only
  # - torchvision # dlc-only
  - pip: # Items also in pyproject removed
      - ghostipy # for common_filter
      # - tensorflow<=2.12 # dlc-only
      - .
