# This file is used to associate data in the corresponding NWB file with new (to-be-created) entities or
# existing entities.
# - If the entity does not exist, then the user will be prompted to create a new entity.
# - If the entity exists, then values that are not primary keys will be ignored.
# Subject:
# - subject_id: My Subject  # this value is used instead of the subject_id in the NWB file
#   age: 7 months  # if `subject_id: My Subject` does not already exist in Subject, then this is used to define the new entity

# Institution:
# - institution_name: DEF University  # this value is used instead of the subject_id in the NWB file

# Lab:
# - lab_name: ABC Lab  # this value is used instead of the subject_id in the NWB file

# LabMember:
# - lab_member_name: Grad Student One  # this value is used instead of the subject_id in the NWB file


# the user has two options to associate the NWB file with a "Neuropixels Recording Device" data acquisition device
# that does not exist in the database.
# 1. the user can first define the entry outside of this file, either using DataJoint commands or
#    spyglass.populate_from_yaml. then in this file, the user would refer to that entry by primary key
#    (data_acquisition_device_name) only. note that additional keys provided here are ignored.
# 2. the user can define the entry here and by doing so, the new data acquisition device entry will be associated with
#    the NWB file. note that if the entry already exists, the existing entry will be used and any non-primary keys
#    specified here will be ignored.

# Probe:
# - probe_id: Neuropixels 1.0 Giocomo Lab Configuration  # every lab/researcher may have a different channel map / configuration for a Neuropixels 1.0 probe
#   probe_type: Neuropixels 1.0  # foreign key to ProbeType
#   contact_side_numbering: True
#   data_acquisition_device_name: Neuropixels Recording Device  # foreign key to DataAcquisitionDevice
#   device_name_to_read_from_nwb_file: Device  # this is different!!!

# TODO if the probe_id already exists but has different values, then the new values are not used
# TODO how to replace probe information when it is in the NWB file?

# this links the NWB file with the Probe via Electrode because Electrode is downstream of Session
Electrode:
- electrode_id: 0
  probe_id: Neuropixels 1.0 Giocomo Lab Configuration
  probe_shank: 0
  probe_electrode: 0

ElectrodeGroup:
- electrode_group_name: shank0

# this links the NWB file with this Data Acquisition Device which must exist in the DB
SessionDataAcquisitionDevice:
- data_acquisition_device_name: Neuropixels Recording Device