# This file is used to associate data in the corresponding NWB file with new (to-be-created) entities or
# existing entities.
# - If the entity does not exist, then the user will be prompted to create a new entity.
# - If the entity exists, then values that are not primary keys will be ignored.

# Subject:
#   subject_id: My Subject  # this value is used instead of the subject_id in the NWB file
#   age: 7 months  # if `subject_id: My Subject` does not already exist in Subject, then this is used to define the new entity

# Institution:
#   institution_name: DEF University  # this value is used instead of the subject_id in the NWB file

# Lab:
#   lab_name: ABC Lab  # this value is used instead of the subject_id in the NWB file

# LabMember:
# - lab_member_name: Grad Student One  # this value is used instead of the subject_id in the NWB file

DataAcquisitionDevice:
- device_name: Neuropixels Recording Device
  system: Neuropixels Acquisition System  # foreign key to DataAcquisitionDeviceSystem
  amplifier: Neuropixels Headstage  # foreign key to DataAcquisitionDeviceAmplifier
  # if these foreign keys do not exist, the user will be prompted to create them


# By default, specifying Probe at the root of the YAML file will create a new Probe
Probe:
- probe_id: Neuropixels 1.0 Giocomo Lab Configuration  # every lab/researcher may have a different channel map / configuration for a Neuropixels 1.0 probe
  probe_type: Neuropixels 1.0  # foreign key to ProbeType
  contact_side_numbering: True
  device_name_to_read_from_nwb_file: Device
  device_name: Neuropixels Recording Device  # foreign key to DataAcquisitionDevice

# TODO if the probe_id already exists but has different values, then the new values are not used
# TODO how to replace probe information when it is in the NWB file?