"""Real-data integration tests for SLEAP processing.

Uses ``tests/_data/sleap/real_robot.analysis.h5``, a genuine SLEAP
.analysis.h5 file generated by running sleap-track on a small robot video
from the SLEAP test suite (166 frames, 2 bodyparts A/B, 1 track).
See ``tests/_data/sleap/make_real_analysis_h5.py`` for provenance details.
"""

import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

DATA_DIR = Path(__file__).parents[2] / "_data" / "sleap"
REAL_H5 = DATA_DIR / "real_robot.analysis.h5"
VIDEO_3FR = DATA_DIR / "small_robot_3_frame.mp4"
MODEL_DIR = DATA_DIR / "model"

# Expected properties of the real fixture
_N_FRAMES = 166
_BODYPARTS = ["A", "B"]
_SCORER = "track_0"
# Pinned from inference on small_robot.mp4 frame 0 (SLEAP 1.6.3, sleap-nn 0.2.0)
_FRAME0_A_X = 319.797
_FRAME0_A_Y = 47.925


# ── parse on real data ───────────────────────────────────────────────────────


class TestRealSLEAPParse:
    """parse_sleap_analysis_h5 returns correct structure from real output."""

    @pytest.fixture(autouse=True)
    def _parse(self):
        from spyglass.position.utils.sleap_io import parse_sleap_analysis_h5

        self._parse = parse_sleap_analysis_h5

    def test_frame_count(self):
        df = self._parse(REAL_H5)
        assert len(df) == _N_FRAMES

    def test_bodyparts_and_coords(self):
        df = self._parse(REAL_H5)
        bps = df.columns.get_level_values("bodyparts").unique().tolist()
        assert sorted(bps) == _BODYPARTS
        coords = df.columns.get_level_values("coords").unique().tolist()
        assert set(coords) == {"x", "y", "likelihood"}

    def test_coordinate_ranges(self):
        # Regression: old axis bug produced ~1.0 pixel coords instead of real
        # O(100) values, and 1 frame instead of 166.
        df = self._parse(REAL_H5)
        for bp in _BODYPARTS:
            x = df[(bp, "x")].dropna().values
            y = df[(bp, "y")].dropna().values
            assert len(x) > 0, f"{bp}.x is entirely NaN"
            assert (x > 10).all(), f"{bp}.x too small (axis-order bug?)"
            assert (y > 10).all(), f"{bp}.y too small (axis-order bug?)"
            # video is 320 px tall × 560 px wide
            assert (x < 600).all(), f"{bp}.x exceeds video width"
            assert (y < 400).all(), f"{bp}.y exceeds video height"

    def test_first_frame_pinned_values(self):
        # Pinned coordinate guard against silent regressions in the parser.
        df, scorer, bps = self._parse(REAL_H5, return_metadata=True)
        assert scorer == _SCORER
        assert sorted(bps) == _BODYPARTS
        assert abs(df.loc[0, ("A", "x")] - _FRAME0_A_X) < 0.1
        assert abs(df.loc[0, ("A", "y")] - _FRAME0_A_Y) < 0.1


# ── 3-level MultiIndex promotion ─────────────────────────────────────────────


class TestRealSLEAPLoad:
    """Mirrors PoseEstim._load_pose_data SLEAP path without DB access."""

    def _load(self, h5_path):
        from spyglass.position.utils.sleap_io import parse_sleap_analysis_h5

        df_2level, scorer, bodyparts = parse_sleap_analysis_h5(
            h5_path, return_metadata=True
        )
        df_2level.columns = pd.MultiIndex.from_tuples(
            [(scorer, bp, coord) for bp, coord in df_2level.columns],
            names=["scorer", "bodyparts", "coords"],
        )
        return df_2level, scorer, bodyparts

    def test_three_level_multiindex(self):
        df, scorer, bps = self._load(REAL_H5)
        assert df.columns.nlevels == 3
        assert df.columns.names == ["scorer", "bodyparts", "coords"]
        assert scorer == _SCORER
        assert sorted(bps) == _BODYPARTS
        assert len(df) == _N_FRAMES


# ── compute_pose_outputs smoke tests ─────────────────────────────────────────


def _real_df_with_timestamps():
    """Return parsed real_robot DF with fake 30 Hz timestamps as index."""
    from spyglass.position.utils.sleap_io import parse_sleap_analysis_h5

    df_2level, scorer, _ = parse_sleap_analysis_h5(
        REAL_H5, return_metadata=True
    )
    df_2level.columns = pd.MultiIndex.from_tuples(
        [(scorer, bp, coord) for bp, coord in df_2level.columns],
        names=["scorer", "bodyparts", "coords"],
    )
    df_2level.index = np.arange(_N_FRAMES) / 30.0
    return df_2level


_SMOOTH_NONE = {
    "interpolate": False,
    "smooth": False,
    "likelihood_thresh": 0.0,
}
_CENTROID_1PT = {"method": "1pt", "points": {"point1": "A"}}
_CENTROID_2PT = {
    "points": {"point1": "A", "point2": "B"},
    "max_LED_separation": 560.0,
}
_ORIENT_NONE = {"method": "none"}
_ORIENT_2PT = {
    "method": "two_pt",
    "bodypart1": "A",
    "bodypart2": "B",
    "smooth": False,
}


class TestRealSLEAPProcess:
    """compute_pose_outputs on real SLEAP data: shape and finiteness."""

    @pytest.fixture(autouse=True)
    def fn(self):
        from spyglass.position.utils.pose_processing import compute_pose_outputs

        self.fn = compute_pose_outputs

    def test_1pt_centroid_no_smooth_shape(self):
        df = _real_df_with_timestamps()
        result = self.fn(df, _ORIENT_NONE, _CENTROID_1PT, _SMOOTH_NONE)
        assert result["centroid"].shape == (_N_FRAMES, 2)
        assert result["speed"].shape == (_N_FRAMES,)
        assert result["orientation"].shape == (_N_FRAMES,)
        assert result["sampling_rate"] == pytest.approx(30.0, rel=0.01)

    def test_2pt_centroid_orient_finite(self):
        pytest.importorskip("bottleneck")
        df = _real_df_with_timestamps()
        smooth = {
            **_SMOOTH_NONE,
            "interpolate": True,
            "smooth": True,
            "smoothing_params": {
                "method": "moving_avg",
                "smoothing_duration": 0.05,
            },
        }
        result = self.fn(df, _ORIENT_2PT, _CENTROID_2PT, smooth)
        for key in ("centroid", "velocity_2d", "speed", "orientation"):
            arr = result[key]
            assert not np.any(np.isinf(arr)), f"{key} has inf values"
        # centroid should not be all-NaN
        assert not np.all(np.isnan(result["centroid"][:, 0]))


# ── live inference round-trip ─────────────────────────────────────────────────


class TestLiveSLEAPInference:
    """Run sleap-track → analysis.h5 → parse.  Skipped without SLEAP."""

    @pytest.fixture(autouse=True)
    def skip_if_no_sleap(self, skip_if_no_sleap):  # noqa: F811
        pass

    @pytest.fixture
    def sleap_cli(self):
        import shutil

        cli = shutil.which("sleap-track")
        if cli is None:
            pytest.skip("sleap-track CLI not found in PATH")
        return cli

    @pytest.fixture
    def model_dir(self):
        if not MODEL_DIR.exists():
            pytest.skip(f"Model directory not found: {MODEL_DIR}")
        return MODEL_DIR

    def test_3frame_inference_round_trip(self, sleap_cli, model_dir):
        """Inference on 3-frame clip → .analysis.h5 → parser returns 3 frames."""
        import sleap_io

        from spyglass.position.utils.sleap_io import parse_sleap_analysis_h5

        with tempfile.TemporaryDirectory() as tmp:
            slp_path = Path(tmp) / "out.predictions.slp"
            h5_path = Path(tmp) / "out.analysis.h5"

            result = subprocess.run(
                [
                    "sleap-track",
                    str(VIDEO_3FR),
                    "-m",
                    str(model_dir),
                    "--cpu",
                    "-o",
                    str(slp_path),
                ],
                capture_output=True,
                text=True,
            )
            assert (
                result.returncode == 0
            ), f"sleap-track failed:\n{result.stderr}"
            assert slp_path.exists(), "sleap-track produced no output file"

            labels = sleap_io.load_file(str(slp_path))
            sleap_io.save_analysis_h5(labels, str(h5_path))

            df, scorer, bps = parse_sleap_analysis_h5(
                h5_path, return_metadata=True
            )

        assert len(df) == 3, f"Expected 3 frames, got {len(df)}"
        assert sorted(bps) == _BODYPARTS
        x = df[("A", "x")].dropna().values
        assert (x > 10).all(), "x coordinates too small (axis-order bug?)"
