"""Synthetic drifting-recording fixtures for the motion-estimation tests.

One polymer shank (32 contacts in a single column at the 26 um pitch of the
Frank-lab polymer probe, ``_fixtures/mearec_to_nwb.py``) with 30 units,
generated by SpikeInterface's ``generate_drifting_recording`` and bandpassed
600-6000 Hz in float64 like the v2 hippocampus recipe. The drift scenarios
match the development benchmark the test tolerances come from: a rigid zigzag
of +/-25 um with one period over the recording, and the static twin (the same
units and spike trains with zero displacement).

Everything is lazy: traces are generated chunk by chunk, so a 90 s recording
costs about 1 GB peak with estimation (measured with ``/usr/bin/time -l``).
"""

from __future__ import annotations

import numpy as np

PITCH_UM = 26.0
N_CONTACTS = 32
CONTACT_RADIUS_UM = 7.5
SAMPLING_FREQUENCY = 30_000.0
NUM_UNITS = 30
DISPLACEMENT_SAMPLING_FREQUENCY = 5.0
RIGID_AMPLITUDE_UM = 25.0
#: Job kwargs of the development benchmark (serial, 1 s chunks).
JOB_KWARGS = {"n_jobs": 1, "chunk_duration": "1s", "progress_bar": False}


def polymer_shank_probe(n_contacts: int = N_CONTACTS):
    """One single-column shank of ``n_contacts`` at the polymer pitch."""
    from probeinterface import Probe

    positions = np.column_stack(
        [np.zeros(n_contacts), -PITCH_UM * np.arange(n_contacts)]
    )
    probe = Probe(ndim=2, si_units="um")
    probe.set_contacts(
        positions=positions,
        shapes="circle",
        shape_params={"radius": CONTACT_RADIUS_UM},
    )
    probe.create_auto_shape(probe_type="tip")
    probe.set_device_channel_indices(np.arange(n_contacts))
    return probe


def bandpass(recording):
    """The v2 hippocampus band (600-6000 Hz), float64."""
    import spikeinterface.preprocessing as sip

    return sip.bandpass_filter(
        recording, freq_min=600.0, freq_max=6000.0, dtype=np.float64
    )


def rigid_drift_recordings(*, seed: int, duration_s: float):
    """Bandpassed rigid-zigzag drifting recording and its static twin.

    Returns
    -------
    drifting, static : si.BaseRecording
        Bandpassed recordings with the same units and spikes.
    displacement : numpy.ndarray
        ``(n_t,)`` ground-truth rigid displacement (um) sampled at
        ``DISPLACEMENT_SAMPLING_FREQUENCY``, in SpikeInterface ``Motion``'s
        sign convention (the generator adds it to unit depth).
    """
    from spikeinterface.generation import generate_drifting_recording

    static, drifting, _sorting, extra = generate_drifting_recording(
        num_units=NUM_UNITS,
        duration=duration_s,
        sampling_frequency=SAMPLING_FREQUENCY,
        probe=polymer_shank_probe(),
        extra_outputs=True,
        seed=seed,
        generate_displacement_vector_kwargs=dict(
            displacement_sampling_frequency=DISPLACEMENT_SAMPLING_FREQUENCY,
            drift_start_um=[0, RIGID_AMPLITUDE_UM],
            drift_stop_um=[0, -RIGID_AMPLITUDE_UM],
            drift_step_um=1,
            motion_list=[
                dict(
                    drift_mode="zigzag",
                    non_rigid_gradient=None,
                    t_start_drift=0.0,
                    t_end_drift=None,
                    period_s=duration_s,
                )
            ],
        ),
    )
    displacement = extra["displacement_vectors"][:, 1, 0].astype(float)
    return bandpass(drifting), bandpass(static), displacement


def common_frame_error(motion, displacement, channel_depths):
    """Estimate-minus-truth error after removing one global offset (um).

    The estimate is evaluated at every channel depth at each of its temporal
    bin centers; the truth is the mean ground-truth displacement over each
    temporal bin. DREDge centres its estimate on its own data (an arbitrary
    reference), so one offset over all bins and depths is removed before the
    error is summarized -- the same metric as the development benchmark.

    Returns
    -------
    rms, max_abs : float
    """
    edges = motion.temporal_bin_edges_s[0]
    centers = motion.temporal_bins_s[0]
    sample_times = (
        np.arange(displacement.size) + 0.5
    ) / DISPLACEMENT_SAMPLING_FREQUENCY
    truth = np.array(
        [
            displacement[(sample_times >= lo) & (sample_times < hi)].mean()
            for lo, hi in zip(edges[:-1], edges[1:])
        ]
    )
    estimate = np.stack(
        [
            motion.get_displacement_at_time_and_depth(
                np.full(channel_depths.size, center), channel_depths
            )
            for center in centers
        ]
    )
    diff = estimate - truth[:, None]
    diff -= diff.mean()
    return float(np.sqrt(np.mean(diff**2))), float(np.max(np.abs(diff)))


def plant_artifact_bursts(
    recording, windows_s, *, rate_hz: float, amplitude_uv: float
):
    """Add stationary, spike-shaped artifact bursts to ``recording``.

    Inside each ``(start_s, end_s)`` window a large biphasic transient
    (``amplitude_uv`` peak, 1 ms long) fires at ``rate_hz`` on the top eight
    contacts at a FIXED depth, so it does not drift with the units: unmasked,
    it is strong, motion-free evidence at the bins it occupies.

    Returns
    -------
    si.BaseRecording
        The recording with the bursts injected (lazy).
    list[tuple[int, int]]
        Half-open frame ranges covering each burst plus 5 ms either side --
        the ranges an artifact mask would silence.
    """
    from spikeinterface.core import NumpySorting
    from spikeinterface.core.generate import InjectTemplatesRecording

    fs = recording.get_sampling_frequency()
    n_template = int(round(1e-3 * fs))
    t = np.linspace(-1.0, 1.0, n_template)
    waveform = -amplitude_uv * np.exp(-8.0 * t**2) * (1.0 - 4.0 * t**2)
    template = np.zeros((1, n_template, recording.get_num_channels()))
    template[0, :, :8] = waveform[:, None]
    times, ranges = [], []
    pad = int(round(5e-3 * fs))
    for start_s, end_s in windows_s:
        frames = np.arange(
            int(start_s * fs), int(end_s * fs), int(round(fs / rate_hz))
        )
        times.append(frames)
        ranges.append(
            (int(frames[0]) - pad, int(frames[-1]) + n_template + pad)
        )
    frames = np.concatenate(times)
    sorting = NumpySorting.from_samples_and_labels(
        [frames], [np.zeros(frames.size, dtype=int)], fs
    )
    injected = InjectTemplatesRecording(
        sorting,
        template.astype(recording.get_dtype()),
        nbefore=n_template // 2,
        parent_recording=recording,
    )
    return injected, ranges


#: Probe type of the single-shank ingestible fixture. Distinct from the 4-shank
#: polymer type so its one-shank ``Probe`` rows never collide with that probe's.
SINGLE_SHANK_PROBE_TYPE = "polymer-1shank-32ch-26um-sim"


def write_drifting_polymer_nwb(
    out_path, *, session_start, fixture_name: str, seed: int, duration_s: float
):
    """Write an ingestible one-shank polymer session with planted rigid drift.

    The raw (unfiltered) traces of :func:`rigid_drift_recordings`'s drifting
    recording go into the Frank-lab NWB layout the MEArec fixtures use, so
    ``insert_sessions`` and the v2 recording stage accept it.

    Returns
    -------
    pathlib.Path
        ``out_path``.
    """
    from pathlib import Path

    import pynwb
    from spikeinterface.generation import generate_drifting_recording

    from spyglass.spikesorting.v2._fixtures.mearec_to_nwb import (
        ProbeContact,
        ProbeLayout,
        _add_probe_and_electrodes,
        _add_raw_ephys,
        _build_nwbfile,
    )

    layout = ProbeLayout(
        probe_type=SINGLE_SHANK_PROBE_TYPE,
        description="one 32-contact shank of a polymer probe, simulated",
        contact_size_um=2 * CONTACT_RADIUS_UM,
        contact_side_numbering=True,
        contacts=tuple(
            ProbeContact(
                electrode_id=i,
                shank_id=0,
                rel_x=0.0,
                rel_y=-PITCH_UM * i,
                rel_z=0.0,
            )
            for i in range(N_CONTACTS)
        ),
    )
    _static, drifting, _sorting, _extra = generate_drifting_recording(
        num_units=NUM_UNITS,
        duration=duration_s,
        sampling_frequency=SAMPLING_FREQUENCY,
        probe=polymer_shank_probe(),
        extra_outputs=True,
        seed=seed,
        generate_displacement_vector_kwargs=dict(
            displacement_sampling_frequency=DISPLACEMENT_SAMPLING_FREQUENCY,
            drift_start_um=[0, RIGID_AMPLITUDE_UM],
            drift_stop_um=[0, -RIGID_AMPLITUDE_UM],
            drift_step_um=1,
            motion_list=[
                dict(
                    drift_mode="zigzag",
                    non_rigid_gradient=None,
                    t_start_drift=0.0,
                    t_end_drift=None,
                    period_s=duration_s,
                )
            ],
        ),
    )
    nwbfile = _build_nwbfile(
        fixture_name=fixture_name, session_start=session_start
    )
    _add_probe_and_electrodes(nwbfile, layout=layout, targeted_location="CA1")
    _add_raw_ephys(
        nwbfile,
        traces=drifting.get_traces(return_in_uV=True),
        sampling_frequency=SAMPLING_FREQUENCY,
    )
    out_path = Path(out_path)
    with pynwb.NWBHDF5IO(str(out_path), mode="w") as io:
        io.write(nwbfile)
    return out_path
