"""Synthetic drifting-recording fixtures for the motion-estimation tests.

One polymer shank (32 contacts in a single column at the 26 um pitch of the
Frank-lab polymer probe, ``_fixtures/mearec_to_nwb.py``) with 30 units,
generated by SpikeInterface's ``generate_drifting_recording`` and bandpassed
600-6000 Hz in float64 like the v2 hippocampus recipe. The drift scenarios
match the development benchmark the test tolerances come from: a rigid zigzag
of +/-25 um with one period over the recording, and the static twin (the same
units and spike trains with zero displacement).

Everything is lazy: traces are generated chunk by chunk, so a 90 s recording
costs about 1 GB peak with estimation (measured with ``/usr/bin/time -l``).
"""

from __future__ import annotations

from contextlib import contextmanager

import numpy as np

PITCH_UM = 26.0
N_CONTACTS = 32
CONTACT_RADIUS_UM = 7.5
SAMPLING_FREQUENCY = 30_000.0
NUM_UNITS = 30
DISPLACEMENT_SAMPLING_FREQUENCY = 5.0
RIGID_AMPLITUDE_UM = 25.0
#: Job kwargs of the development benchmark (serial, 1 s chunks).
JOB_KWARGS = {"n_jobs": 1, "chunk_duration": "1s", "progress_bar": False}


def polymer_shank_probe(n_contacts: int = N_CONTACTS):
    """One single-column shank of ``n_contacts`` at the polymer pitch."""
    from probeinterface import Probe

    positions = np.column_stack(
        [np.zeros(n_contacts), -PITCH_UM * np.arange(n_contacts)]
    )
    probe = Probe(ndim=2, si_units="um")
    probe.set_contacts(
        positions=positions,
        shapes="circle",
        shape_params={"radius": CONTACT_RADIUS_UM},
    )
    probe.create_auto_shape(probe_type="tip")
    probe.set_device_channel_indices(np.arange(n_contacts))
    return probe


def bandpass(recording):
    """The v2 hippocampus band (600-6000 Hz), float64."""
    import spikeinterface.preprocessing as sip

    return sip.bandpass_filter(
        recording, freq_min=600.0, freq_max=6000.0, dtype=np.float64
    )


def rigid_drift_recordings(
    *, seed: int, duration_s: float, noise_free: bool = False
):
    """Bandpassed rigid-zigzag drifting recording and its static twin.

    ``noise_free`` generates the spikes without background noise, so the two
    twins differ only where the units moved.

    Returns
    -------
    drifting, static : si.BaseRecording
        Bandpassed recordings with the same units and spikes.
    displacement : numpy.ndarray
        ``(n_t,)`` ground-truth rigid displacement (um) sampled at
        ``DISPLACEMENT_SAMPLING_FREQUENCY``, in SpikeInterface ``Motion``'s
        sign convention (the generator adds it to unit depth).
    """
    from spikeinterface.generation import generate_drifting_recording

    static, drifting, _sorting, extra = generate_drifting_recording(
        num_units=NUM_UNITS,
        duration=duration_s,
        sampling_frequency=SAMPLING_FREQUENCY,
        probe=polymer_shank_probe(),
        extra_outputs=True,
        seed=seed,
        generate_displacement_vector_kwargs=dict(
            displacement_sampling_frequency=DISPLACEMENT_SAMPLING_FREQUENCY,
            drift_start_um=[0, RIGID_AMPLITUDE_UM],
            drift_stop_um=[0, -RIGID_AMPLITUDE_UM],
            drift_step_um=1,
            motion_list=[
                dict(
                    drift_mode="zigzag",
                    non_rigid_gradient=None,
                    t_start_drift=0.0,
                    t_end_drift=None,
                    period_s=duration_s,
                )
            ],
        ),
        **(
            {"generate_noise_kwargs": {"noise_levels": 0.0}}
            if noise_free
            else {}
        ),
    )
    displacement = extra["displacement_vectors"][:, 1, 0].astype(float)
    return bandpass(drifting), bandpass(static), displacement


def _step_displacement_data(
    duration_s: float,
    change_times_s,
    levels_um,
    num_units: int,
    steps_um=None,
):
    """``generate_drifting_recording`` displacement data for rigid steps.

    Displacement is ``levels_um[0]`` until ``change_times_s[0]``, then
    ``levels_um[1]`` until ``change_times_s[1]``, and so on, for every unit
    (rigid). Templates are generated at the displacements ``steps_um``
    (default: every 1 um within +/-15 um); each level must be one of them.
    """
    from spikeinterface.generation.drift_tools import make_linear_displacement

    n_t = int(np.ceil(DISPLACEMENT_SAMPLING_FREQUENCY * duration_s))
    times = np.arange(n_t) / DISPLACEMENT_SAMPLING_FREQUENCY
    vector = np.asarray(levels_um, dtype=float)[
        np.searchsorted(np.asarray(change_times_s), times, side="right")
    ]
    displacement_vectors = np.zeros((n_t, 2, 1))
    displacement_vectors[:, 1, 0] = vector
    unit_displacements = np.zeros((n_t, num_units, 2))
    unit_displacements[:, :, 1] = vector[:, None]
    if steps_um is None:
        steps = make_linear_displacement(
            np.array([0.0, 15.0]), np.array([0.0, -15.0]), num_step=31
        )
    else:
        steps = np.column_stack(
            [np.zeros(len(steps_um)), np.asarray(steps_um, dtype=float)]
        )
    return (
        unit_displacements,
        displacement_vectors,
        np.ones((num_units, 1)),
        DISPLACEMENT_SAMPLING_FREQUENCY,
        steps,
    )


def stepped_recordings_in_windows(
    *,
    seed: int,
    windows_s,
    change_times_s,
    levels_um,
    steps_um=None,
    noise_free: bool = False,
):
    """Keep only some windows of one recording with planted rigid steps.

    One recording lasting until the last window's end is generated with
    rigid steps (:func:`_step_displacement_data`, templates at ``steps_um``),
    bandpassed as a whole (the v2 recording stage filters before it restricts
    to the selected intervals), and cut to ``windows_s``. Steps placed
    between two windows happen where no sample was kept. The static twin is
    cut the same way. ``noise_free`` generates the spikes without background
    noise, so the two twins differ only where the units moved.

    Returns
    -------
    drifting, static : list[si.BaseRecording]
        One bandpassed recording per window, each with the time vector of
        its frames on the generated recording's clock.
    displacement : numpy.ndarray
        ``(n_t,)`` ground-truth rigid displacement (um) over the whole
        generated recording, sampled at ``DISPLACEMENT_SAMPLING_FREQUENCY``.
    """
    from spikeinterface.generation import generate_drifting_recording

    duration_s = float(windows_s[-1][1])
    displacement_data = _step_displacement_data(
        duration_s, change_times_s, levels_um, NUM_UNITS, steps_um=steps_um
    )
    static, drifting, _sorting, _extra = generate_drifting_recording(
        num_units=NUM_UNITS,
        duration=duration_s,
        sampling_frequency=SAMPLING_FREQUENCY,
        probe=polymer_shank_probe(),
        displacement_data=displacement_data,
        extra_outputs=True,
        seed=seed,
        **(
            {"generate_noise_kwargs": {"noise_levels": 0.0}}
            if noise_free
            else {}
        ),
    )

    def _cut(recording):
        filtered = bandpass(recording)
        pieces = []
        for start_s, end_s in windows_s:
            start = int(round(start_s * SAMPLING_FREQUENCY))
            end = int(round(end_s * SAMPLING_FREQUENCY))
            piece = filtered.frame_slice(start, end)
            piece.set_times(
                np.arange(start, end) / SAMPLING_FREQUENCY, with_warning=False
            )
            pieces.append(piece)
        return pieces

    return (
        _cut(drifting),
        _cut(static),
        displacement_data[1][:, 1, 0].astype(float),
    )


def join_windows(pieces):
    """Join per-window recordings into one continuous-frame recording.

    Returns
    -------
    joined : si.BaseRecording
        The windows' frames back to back, on a synthetic clock.
    spans : list[tuple[int, int]]
        One continuity span per window.
    source_start_s : list[float]
        Each window's first timestamp.
    """
    from spikeinterface.core import concatenate_recordings

    ends = np.cumsum([piece.get_num_samples() for piece in pieces])
    spans = [(int(a), int(b)) for a, b in zip([0, *ends[:-1]], ends)]
    starts = [float(piece.sample_index_to_time(0)) for piece in pieces]
    return concatenate_recordings(pieces, ignore_times=True), spans, starts


def jump_across_gap_recordings(
    *, seed: int, span_s: float, gap_s: float, jump_um: float = 30.0
):
    """Two equal spans of one recording with a rigid jump inside the gap.

    ``[0, span_s)`` and ``[span_s + gap_s, 2 * span_s + gap_s)`` of one
    generated recording, with a ``jump_um`` rigid step at the middle of the
    removed gap (:func:`stepped_recordings_in_windows`).

    Returns
    -------
    drifting, static : si.BaseRecording
        The two spans joined (``2 * span_s`` seconds of frames).
    spans : list[tuple[int, int]]
        The two continuity spans in frames.
    source_start_s : list[float]
        Each span's start on the generated recording's clock (s).
    displacement : numpy.ndarray
        ``(n_t,)`` ground-truth rigid displacement (um).
    """
    drifting, static, displacement = stepped_recordings_in_windows(
        seed=seed,
        windows_s=[(0.0, span_s), (span_s + gap_s, 2 * span_s + gap_s)],
        change_times_s=[span_s + gap_s / 2],
        levels_um=[-jump_um / 2, jump_um / 2],
    )
    joined, spans, starts = join_windows(drifting)
    joined_static, _, _ = join_windows(static)
    return joined, joined_static, spans, starts, displacement


def source_clock_errors(motion, clock, displacement, channel_depths):
    """Estimate-minus-truth of a gapped estimate on bins holding data (um).

    Each temporal bin is mapped to source time
    (``_motion.displacement_on_source_clock``); bins inside a capped gap are
    skipped. The truth of a bin is the mean ground-truth displacement over its
    width on the source clock, clipped to its span. No offset is removed.

    Returns
    -------
    numpy.ndarray
        ``(n_data_bins, n_depths)`` errors.
    """
    from spyglass.spikesorting.v2._motion import displacement_on_source_clock

    mapped = displacement_on_source_clock(motion, clock)
    half_bin = float(np.diff(motion.temporal_bins_s[0][:2])[0]) / 2
    fs = clock.sampling_frequency
    span_start = clock.source_start_s
    span_end = clock.source_end_s + 1 / fs
    sample_times = (
        np.arange(displacement.size) + 0.5
    ) / DISPLACEMENT_SAMPLING_FREQUENCY
    rows = []
    truths = []
    for b in np.flatnonzero(~mapped.in_gap):
        span = mapped.continuity_span[b]
        center = mapped.source_time_s[b]
        lo = max(center - half_bin, span_start[span])
        hi = min(center + half_bin, span_end[span])
        inside = (sample_times >= lo) & (sample_times < hi)
        if not inside.any():
            continue
        truths.append(displacement[inside].mean())
        rows.append(
            motion.get_displacement_at_time_and_depth(
                np.full(channel_depths.size, motion.temporal_bins_s[0][b]),
                channel_depths,
            )
        )
    return np.stack(rows) - np.asarray(truths)[:, None]


def common_frame_summary(errors):
    """RMS and max |error| after removing one offset over all ``errors``."""
    diff = np.asarray(errors) - np.mean(errors)
    return float(np.sqrt(np.mean(diff**2))), float(np.max(np.abs(diff)))


def common_frame_error_on_source_clock(
    motion, clock, displacement, channel_depths
):
    """Common-frame error of a gapped estimate, on bins holding data (um).

    :func:`source_clock_errors` with one offset over all kept bins and depths
    removed, as in :func:`common_frame_error`.

    Returns
    -------
    rms, max_abs : float
    """
    return common_frame_summary(
        source_clock_errors(motion, clock, displacement, channel_depths)
    )


def common_frame_error(motion, displacement, channel_depths):
    """Estimate-minus-truth error after removing one global offset (um).

    The estimate is evaluated at every channel depth at each of its temporal
    bin centers; the truth is the mean ground-truth displacement over each
    temporal bin. DREDge centres its estimate on its own data (an arbitrary
    reference), so one offset over all bins and depths is removed before the
    error is summarized -- the same metric as the development benchmark.

    Returns
    -------
    rms, max_abs : float
    """
    edges = motion.temporal_bin_edges_s[0]
    centers = motion.temporal_bins_s[0]
    sample_times = (
        np.arange(displacement.size) + 0.5
    ) / DISPLACEMENT_SAMPLING_FREQUENCY
    truth = np.array(
        [
            displacement[(sample_times >= lo) & (sample_times < hi)].mean()
            for lo, hi in zip(edges[:-1], edges[1:])
        ]
    )
    estimate = np.stack(
        [
            motion.get_displacement_at_time_and_depth(
                np.full(channel_depths.size, center), channel_depths
            )
            for center in centers
        ]
    )
    diff = estimate - truth[:, None]
    diff -= diff.mean()
    return float(np.sqrt(np.mean(diff**2))), float(np.max(np.abs(diff)))


def plant_artifact_bursts(
    recording, windows_s, *, rate_hz: float, amplitude_uv: float
):
    """Add stationary, spike-shaped artifact bursts to ``recording``.

    Inside each ``(start_s, end_s)`` window a large biphasic transient
    (``amplitude_uv`` peak, 1 ms long) fires at ``rate_hz`` on the top eight
    contacts at a FIXED depth, so it does not drift with the units: unmasked,
    it is strong, motion-free evidence at the bins it occupies.

    Returns
    -------
    si.BaseRecording
        The recording with the bursts injected (lazy).
    list[tuple[int, int]]
        Half-open frame ranges covering each burst plus 5 ms either side --
        the ranges an artifact mask would silence.
    """
    from spikeinterface.core import NumpySorting
    from spikeinterface.core.generate import InjectTemplatesRecording

    fs = recording.get_sampling_frequency()
    n_template = int(round(1e-3 * fs))
    t = np.linspace(-1.0, 1.0, n_template)
    waveform = -amplitude_uv * np.exp(-8.0 * t**2) * (1.0 - 4.0 * t**2)
    template = np.zeros((1, n_template, recording.get_num_channels()))
    template[0, :, :8] = waveform[:, None]
    times, ranges = [], []
    pad = int(round(5e-3 * fs))
    for start_s, end_s in windows_s:
        frames = np.arange(
            int(start_s * fs), int(end_s * fs), int(round(fs / rate_hz))
        )
        times.append(frames)
        ranges.append(
            (int(frames[0]) - pad, int(frames[-1]) + n_template + pad)
        )
    frames = np.concatenate(times)
    sorting = NumpySorting.from_samples_and_labels(
        [frames], [np.zeros(frames.size, dtype=int)], fs
    )
    injected = InjectTemplatesRecording(
        sorting,
        template.astype(recording.get_dtype()),
        nbefore=n_template // 2,
        parent_recording=recording,
    )
    return injected, ranges


#: Probe type of the single-shank ingestible fixture. Distinct from the 4-shank
#: polymer type so its one-shank ``Probe`` rows never collide with that probe's.
SINGLE_SHANK_PROBE_TYPE = "polymer-1shank-32ch-26um-sim"


def write_drifting_polymer_nwb(
    out_path, *, session_start, fixture_name: str, seed: int, duration_s: float
):
    """Write an ingestible one-shank polymer session with planted rigid drift.

    The raw (unfiltered) traces of :func:`rigid_drift_recordings`'s drifting
    recording go into the Frank-lab NWB layout the MEArec fixtures use, so
    ``insert_sessions`` and the v2 recording stage accept it.

    Returns
    -------
    pathlib.Path
        ``out_path``.
    """
    from pathlib import Path

    import pynwb
    from spikeinterface.generation import generate_drifting_recording

    from spyglass.spikesorting.v2._fixtures.mearec_to_nwb import (
        ProbeContact,
        ProbeLayout,
        _add_probe_and_electrodes,
        _add_raw_ephys,
        _build_nwbfile,
    )

    layout = ProbeLayout(
        probe_type=SINGLE_SHANK_PROBE_TYPE,
        description="one 32-contact shank of a polymer probe, simulated",
        contact_size_um=2 * CONTACT_RADIUS_UM,
        contact_side_numbering=True,
        contacts=tuple(
            ProbeContact(
                electrode_id=i,
                shank_id=0,
                rel_x=0.0,
                rel_y=-PITCH_UM * i,
                rel_z=0.0,
            )
            for i in range(N_CONTACTS)
        ),
    )
    _static, drifting, _sorting, _extra = generate_drifting_recording(
        num_units=NUM_UNITS,
        duration=duration_s,
        sampling_frequency=SAMPLING_FREQUENCY,
        probe=polymer_shank_probe(),
        extra_outputs=True,
        seed=seed,
        generate_displacement_vector_kwargs=dict(
            displacement_sampling_frequency=DISPLACEMENT_SAMPLING_FREQUENCY,
            drift_start_um=[0, RIGID_AMPLITUDE_UM],
            drift_stop_um=[0, -RIGID_AMPLITUDE_UM],
            drift_step_um=1,
            motion_list=[
                dict(
                    drift_mode="zigzag",
                    non_rigid_gradient=None,
                    t_start_drift=0.0,
                    t_end_drift=None,
                    period_s=duration_s,
                )
            ],
        ),
    )
    nwbfile = _build_nwbfile(
        fixture_name=fixture_name, session_start=session_start
    )
    _add_probe_and_electrodes(nwbfile, layout=layout, targeted_location="CA1")
    _add_raw_ephys(
        nwbfile,
        traces=drifting.get_traces(return_in_uV=True),
        sampling_frequency=SAMPLING_FREQUENCY,
    )
    out_path = Path(out_path)
    with pynwb.NWBHDF5IO(str(out_path), mode="w") as io:
        io.write(nwbfile)
    return out_path


@contextmanager
def hdf5_timed_recording_with_shared_peak_frame(h5_path, *, gap_s: float):
    """A 2 s, 32-contact recording whose two spikes share one frame.

    Gaussian noise with a -60 unit spike every 50 ms on one contact; the
    first spike fires on contacts 0 and 31 (806 um apart, far outside any
    detection radius) at the same frame, so peak detection returns two peaks
    with one ``sample_index``. The time vector is left as an open HDF5
    dataset, as the v2 NWB reader leaves it: 1 s at ``100 s``, then
    ``gap_s`` of no samples, then 1 s more.

    A context manager: the HDF5 file stays open while it is active.

    Yields
    ------
    recording : si.BaseRecording
    timestamps : numpy.ndarray
        ``(n_samples,)`` the timestamps written to ``h5_path``.
    """
    import h5py
    from spikeinterface.core import NumpyRecording

    n_samples, n_channels = int(2 * SAMPLING_FREQUENCY), N_CONTACTS
    traces = (
        np.random.default_rng(0)
        .normal(size=(n_samples, n_channels))
        .astype("float32")
    )
    waveform = -60.0 * np.exp(-0.5 * (np.arange(-15, 16) / 4.0) ** 2)
    frames = np.arange(3000, n_samples - 3000, 1500)
    for i, frame in enumerate(frames):
        for channel in (0, n_channels - 1) if i == 0 else (i % n_channels,):
            traces[frame - 15 : frame + 16, channel] += waveform
    recording = NumpyRecording([traces], SAMPLING_FREQUENCY)
    recording.set_channel_locations(
        np.column_stack(
            [np.zeros(n_channels), -PITCH_UM * np.arange(n_channels)]
        )
    )
    half = n_samples // 2
    timestamps = (
        100.0
        + np.r_[
            np.arange(half),
            np.arange(half, n_samples) + gap_s * SAMPLING_FREQUENCY,
        ]
        / SAMPLING_FREQUENCY
    )
    with h5py.File(h5_path, "w") as h5:
        h5.create_dataset("timestamps", data=timestamps)
    with h5py.File(h5_path, "r") as h5:
        recording._recording_segments[0].time_vector = h5["timestamps"]
        yield recording, timestamps
