#!/usr/bin/env python3
"""Validate that install.py and settings.py produce compatible configs.

This script verifies that the configuration generated by install.py is compatible
with what settings.py expects. It identifies missing keys that might cause issues.
"""

import json
import sys
from pathlib import Path
from tempfile import TemporaryDirectory

# Add scripts dir to path to import install functions
scripts_dir = Path(__file__).parent
sys.path.insert(0, str(scripts_dir))

from install import build_directory_structure

# Import from spyglass
sys.path.insert(0, str(scripts_dir.parent / "src"))
from spyglass.settings import SpyglassConfig


def get_installer_config_structure(base_dir: Path) -> dict:
    """Get config structure that installer would create."""
    from install import load_directory_schema

    dir_schema = load_directory_schema()
    dirs = build_directory_structure(
        base_dir, schema=dir_schema, create=True, verbose=False
    )

    # Replicate exactly what create_database_config does
    config = {
        # Database connection settings
        "database.host": "localhost",
        "database.port": 3306,
        "database.user": "testuser",
        "database.password": "testpass",
        "database.use_tls": False,
        # DataJoint performance settings
        "filepath_checksum_size_limit": 1 * 1024**3,  # 1 GB
        "enable_python_native_blobs": True,
        # DataJoint stores for external file storage
        "stores": {
            "raw": {
                "protocol": "file",
                "location": str(dirs["spyglass_raw"]),
                "stage": str(dirs["spyglass_raw"]),
            },
            "analysis": {
                "protocol": "file",
                "location": str(dirs["spyglass_analysis"]),
                "stage": str(dirs["spyglass_analysis"]),
            },
        },
        # Spyglass custom configuration
        "custom": {
            "debug_mode": False,
            "test_mode": False,
            "kachery_zone": "franklab.default",
            "spyglass_dirs": {
                "base": str(base_dir),
                "raw": str(dirs["spyglass_raw"]),
                "analysis": str(dirs["spyglass_analysis"]),
                "recording": str(dirs["spyglass_recording"]),
                "sorting": str(dirs["spyglass_sorting"]),
                "waveforms": str(dirs["spyglass_waveforms"]),
                "temp": str(dirs["spyglass_temp"]),
                "video": str(dirs["spyglass_video"]),
                "export": str(dirs["spyglass_export"]),
            },
            "kachery_dirs": {
                "cloud": str(dirs["kachery_cloud"]),
                "storage": str(dirs["kachery_storage"]),
                "temp": str(dirs["kachery_temp"]),
            },
            "dlc_dirs": {
                "base": str(base_dir / "deeplabcut"),
                "project": str(dirs["dlc_project"]),
                "video": str(dirs["dlc_video"]),
                "output": str(dirs["dlc_output"]),
            },
            "moseq_dirs": {
                "base": str(base_dir / "moseq"),
                "project": str(dirs["moseq_project"]),
                "video": str(dirs["moseq_video"]),
            },
        },
    }

    return config


def get_settings_config_structure(base_dir: Path) -> dict:
    """Get config structure that settings.py generates."""
    sg_config = SpyglassConfig()

    config = sg_config._generate_dj_config(
        base_dir=str(base_dir),
        database_user="testuser",
        database_password="testpass",
        database_host="localhost",
        database_port=3306,
        database_use_tls=False,
    )

    return config


def get_all_keys(d: dict, prefix: str = "") -> set:
    """Recursively get all keys in nested dictionary."""
    keys = set()
    for k, v in d.items():
        full_key = f"{prefix}.{k}" if prefix else k
        keys.add(full_key)
        if isinstance(v, dict):
            keys.update(get_all_keys(v, full_key))
    return keys


def compare_configs():
    """Compare config structures and report differences."""
    print("=" * 80)
    print("Config Structure Comparison: install.py vs settings.py")
    print("=" * 80)
    print()

    with TemporaryDirectory() as tmpdir:
        base_dir = Path(tmpdir) / "spyglass_data"

        # Get both config structures
        installer_config = get_installer_config_structure(base_dir)
        settings_config = get_settings_config_structure(base_dir)

        # Get all keys from both
        installer_keys = get_all_keys(installer_config)
        settings_keys = get_all_keys(settings_config)

        # Find differences
        missing_in_installer = settings_keys - installer_keys
        extra_in_installer = installer_keys - settings_keys

        # Report results
        print("MISSING KEYS IN INSTALLER CONFIG:")
        print("-" * 80)
        if missing_in_installer:
            for key in sorted(missing_in_installer):
                print(f"  ❌ {key}")
                # Show value from settings
                parts = key.split(".")
                value = settings_config
                try:
                    for part in parts:
                        value = value[part]
                    print(f"     Expected value: {value}")
                except (KeyError, TypeError):
                    pass
        else:
            print("  ✅ None - all settings.py keys present in installer")

        print()
        print("EXTRA KEYS IN INSTALLER CONFIG:")
        print("-" * 80)
        if extra_in_installer:
            for key in sorted(extra_in_installer):
                print(f"  ⚠️  {key}")
        else:
            print("  ✅ None - installer has no extra keys")

        print()
        print("=" * 80)
        print("SUMMARY:")
        print("=" * 80)

        if not missing_in_installer and not extra_in_installer:
            print("✅ Config structures are IDENTICAL")
            return 0
        elif missing_in_installer:
            print(f"❌ Installer is MISSING {len(missing_in_installer)} keys")
            print(
                "   These keys should be added to install.py::create_database_config()"
            )
            return 1
        else:
            print("⚠️  Installer has extra keys (might be OK)")
            return 0


if __name__ == "__main__":
    sys.exit(compare_configs())
