name: Publish docs
on:
  push:
    tags: # See PEP 440 for valid version format
      - "*.*.*" # For docs bump, use X.X.XaX
    branches:
      - test_branch

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ${{ github.repository_owner }}
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup - pip & config
        run: |
          pip install .[docs]
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy
        run: |
          FULL_VERSION=${{ github.ref }}
          export MAJOR_VERSION=${FULL_VERSION:0:3}
          echo "OWNER: ${REPO_OWNER}. BUILD: ${MAJOR_VERSION}"
          bash ./docs/build-docs.sh push $REPO_OWNER
        env:
          USERNAME: github-actions[bot]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
