name: Tests

on:
  push:
    branches: 
      - '!test_branch'
      - '!documentation'
  schedule:  # once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Manually trigger with 'Run workflow' button

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash -l {0}
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
      UCSF_BOX_TOKEN: ${{ secrets.UCSF_BOX_TOKEN }} # for download and testing
      UCSF_BOX_USER: ${{ secrets.UCSF_BOX_USER }}
      QT_QPA_PLATFORM: 'offscreen' # QT headless
      TF_ENABLE_ONEDNN_OPTS: 0 # TF disable approx calcs
      TF_CPP_MIN_LOG_LEVEL: 2 # Disable TF warnings
    services:
      mysql:
        image: datajoint/mysql:8.0
        env:
          MYSQL_DATABASE: localhost
          MYSQL_ROOT_PASSWORD: tutorial
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.11.0
      if: ${{ !env.ACT }}
      with:
        access_token: ${{ github.token }}
        all_but_latest: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: cuda 
      uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '12.4.1'
    - name: cuda printout
      run: |
        echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
        echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
        nvcc -V
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON }}
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: spyglass-dlc
        environment-file: environment_dlc.yml
        # activate-environment: spyglass
        # environment-file: environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
    - name: pip/apt install
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb # Manage DLC Qt headless
        pip install --quiet .[test,dlc]
    - name: Download data
      env:
        WEBSITE: ftps://ftp.box.com/trodes_to_nwb_test_data/minirec20230622.nwb
        RAW_DIR: /home/runner/work/spyglass/spyglass/tests/_data/raw/ 
        VIDEO_DIR: /home/runner/work/spyglass/spyglass/tests/_data/video/ 
        DLC_DIR: /home/runner/work/spyglass/spyglass/tests/_data/deeplabcut/ 
      run: |
        mkdir -p $RAW_DIR $VIDEO_DIR $DLC_DIR
        wget --recursive --no-verbose --no-host-directories --no-directories \
          --user $UCSF_BOX_USER --password $UCSF_BOX_TOKEN \
          -P $RAW_DIR $WEBSITE
    - name: Run tests
      run: |
        pytest --no-docker tests/common/test_behav.py -k test_invalid_interval 
