name: Test conda env and run tests

on:
  push:
    branches: 
      - '!test_branch'
      - '!documentation'
  schedule:  # once a day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Manually trigger with 'Run workflow' button

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    defaults:
     run:
       shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
        all_but_latest: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON }}
    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: spyglass-dlc
        environment-file: environment_dlc.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
    - name: pip/apt install
      run: |
        pip install --quiet -e .[test,dlc]
        sudo apt-get install -y xvfb # Manage DLC Qt headless
    - name: Download data
      env:
        UCSF_BOX_TOKEN: ${{ secrets.UCSF_BOX_TOKEN }}
        UCSF_BOX_USER: ${{ secrets.UCSF_BOX_USER }}
        WEBSITE: ftps://ftp.box.com/trodes_to_nwb_test_data/
        RAW_DIR: /home/runner/work/spyglass/spyglass/tests/_data/raw/ 
        VIDEO_DIR: /home/runner/work/spyglass/spyglass/tests/_data/video/ 
        DLC_DIR: /home/runner/work/spyglass/spyglass/tests/_data/deeplabcut/ 
      run: |
        mkdir -p $RAW_DIR $VIDEO_DIR $DLC_DIR
        wget --recursive --no-verbose --no-host-directories --no-directories \
          --user $UCSF_BOX_USER --password $UCSF_BOX_TOKEN \
          -P $RAW_DIR $WEBSITE
        mv ${RAW_DIR}*.h264 $VIDEO_DIR
        mv ${RAW_DIR}minirec_dlc_items/* $DLC_DIR
    - name: Run tests
      run: |
        pytest -rP  # env vars are set within certain tests
