name: Import test

on: push

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  #, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    services:
      datajoint_test_server:
        image: datajoint/mysql
        ports:
        - 3306:3306
        options: >-
          -e MYSQL_ROOT_PASSWORD=tutorial
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: nwb_datajoint
        environment-file: environment.yml
    - name: Install nwb_datajoint
      shell: bash -l {0}
      run: |
        conda activate nwb_datajoint
        pip install -e .
    - name: Test configuring datajoint and import
      shell: bash -l {0}
      run: |
        conda activate nwb_datajoint
        python tests/ci_config.py  # configure datajoint and environment vars
        python -c "import nwb_datajoint; import nwb_datajoint.common"  # test import
