name: Run coverage

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  #, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda update conda
        python -m pip install --upgrade pip
        conda env create -f environment.yml
        conda activate nwb_datajoint
        pip install -e .
    - name: Start tutorial docker container
      run: |
        docker run -d --rm --name datajoint-test-server -p 3306:3306 -e MYSQL_ROOT_PASSWORD=tutorial datajoint/mysql
    - name: Configure datajoint
      run: |
        python tests/ci_config.py
    - name: Test import
      run: |
        python -c "import nwb_datajoint; import nwb_datajoint.common"
