"""Tests for the SQL grant strings generated by ``DatabaseSettings``.

These tests only inspect generated SQL text, so no database server is
required. See issue #1065: the ``dj_user`` role must not be able to create
tables in shared schema prefixes.
"""

import pytest

# Privileges the `dj_user` role must hold on shared prefixes, in the order
# MySQL uses when it echoes a grant back via `SHOW GRANTS`.
SHARED_PRIVS = [
    "SELECT",
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "REFERENCES",
    "INDEX",
    "ALTER",
    "LOCK TABLES",
]


@pytest.fixture(scope="module")
def db_settings():
    """A DatabaseSettings instance that never touches a server."""
    from spyglass.utils.database_settings import DatabaseSettings

    return DatabaseSettings(
        user_name="test_user",
        host_name="localhost",
        debug=True,
        exec_user="root",
        exec_pass="unused",
    )


@pytest.fixture(scope="module")
def shared_modules(db_settings):
    """Escaped shared module prefixes, e.g. ``common\\_%``."""
    return db_settings.shared_modules


@pytest.fixture(scope="module")
def user_role_sql(db_settings):
    """The list of SQL statements defining the `dj_user` role."""
    return db_settings._create_roles_dict["user"]


def _shared_grants(sql_lines, shared_modules):
    """Return the grant lines that target a shared module prefix."""
    return [
        line
        for line in sql_lines
        if any(f"`{module}`" in line for module in shared_modules)
    ]


def test_user_role_shared_grants_cover_all_modules(
    user_role_sql, shared_modules
):
    """Every shared prefix still gets an explicit `dj_user` grant."""
    grants = _shared_grants(user_role_sql, shared_modules)
    assert len(grants) == len(shared_modules)


def test_user_role_shared_grants_omit_create(user_role_sql, shared_modules):
    """`dj_user` may not create tables in shared prefixes. See #1065."""
    for line in _shared_grants(user_role_sql, shared_modules):
        assert "CREATE" not in line, f"CREATE granted on shared prefix: {line}"
        assert "ALL PRIVILEGES" not in line, f"Blanket grant: {line}"


def test_user_role_shared_grants_list_privileges(user_role_sql, shared_modules):
    """`dj_user` keeps every non-create privilege on shared prefixes."""
    grants = _shared_grants(user_role_sql, shared_modules)
    expect = ", ".join(SHARED_PRIVS)
    for line in grants:
        assert line.startswith(f"GRANT {expect} ON "), f"Unexpected: {line}"


def test_user_role_keeps_global_select(user_role_sql):
    """`dj_user` still reads every schema."""
    assert "GRANT SELECT, REFERENCES ON `%`.* TO `dj_user`;\n" in user_role_sql


@pytest.mark.parametrize("role", ["guest", "collab", "user"])
def test_global_select_carries_references(db_settings, role):
    """Every role that can read a schema can also reference it.

    A foreign key needs ``REFERENCES`` on the *parent* table, so a role with
    ``SELECT`` alone cannot declare a table pointing at any schema it does not
    own -- including the shared prefixes it is meant to build on.
    """
    grants = [
        line
        for line in db_settings._create_roles_dict[role]
        if "`%`.*" in line and "GRANT" in line and "TO `dj_" in line
    ]
    assert grants, f"No global grant found for {role}"
    for line in grants:
        assert "SELECT" in line, f"Lost SELECT for {role}: {line}"
        assert "REFERENCES" in line, f"Missing REFERENCES for {role}: {line}"


@pytest.mark.parametrize("role", ["guest", "collab", "user"])
def test_global_grant_adds_nothing_else(db_settings, role):
    """The global grant widens to REFERENCES only -- no write privileges."""
    (line,) = [
        ln
        for ln in db_settings._create_roles_dict[role]
        if "`%`.*" in ln and "GRANT" in ln and "TO `dj_" in ln
    ]
    assert line.startswith("GRANT SELECT, REFERENCES ON "), line
    for forbidden in ("INSERT", "UPDATE", "DELETE", "DROP", "CREATE", "ALL"):
        assert forbidden not in line, f"{role} gained {forbidden}: {line}"


def test_add_module_sql_omits_create(db_settings):
    """A newly shared module grants `dj_user` the same restricted set."""
    (line,) = db_settings._add_module_sql("new_module")
    assert "CREATE" not in line
    assert "ALL PRIVILEGES" not in line
    assert line.startswith(f"GRANT {', '.join(SHARED_PRIVS)} ON ")
    assert "`new_module\\_%`.*" in line


def test_user_prefix_grant_unchanged(db_settings):
    """Users retain full control of their own prefix."""
    assert db_settings._user_prefix_sql == [
        "GRANT ALL PRIVILEGES ON `test_user\\_%`.* TO 'test_user'@'%';\n"
    ]


@pytest.mark.parametrize("role", ["guest", "collab"])
def test_non_user_roles_have_no_shared_grants(
    db_settings, shared_modules, role
):
    """Guest and collab roles are untouched by the #1065 fix."""
    assert not _shared_grants(
        db_settings._create_roles_dict[role], shared_modules
    )


def test_admin_role_keeps_all_privileges(db_settings):
    """Admins retain CREATE - they declare new shared tables."""
    assert (
        "GRANT ALL PRIVILEGES ON `%`.* TO `dj_admin`;\n"
        in db_settings._create_roles_dict["admin"]
    )
